#!/bin/sh

/usr/bin/invoke_app "$@" -t rinsidewt \
    -u R-3.4.0 \
    -u wrwroxy-0.1 \
    -w "none" \
    -c "xview -fullscreen -onroot \${R_INSTALL_DIR}/lib/R/library/png/img/Rlogo.png" \
    -c "wrwroxy --stream-log --logfile /dev/null" \
    -C "wtdensityPlain --docroot @tool/bin --http-addr 127.0.0.1 --http-port 8001"
